### ISSUE TITLE
Perspektivering af open source som en løsning og ikke et mål i sig selv

### ISSUE THREAD

**Issue by jeiby** [rammearkitektur/open-source-guidance#10]
Open source kan være løsningen, men hvad er udfordringerne? Åbne systemer og snitflader, leverandøruafhængighed, modulære løsninger, partnerskaber og nye forretningsmodeller brolægger vejen.

**Comment by zorp** [comment]
Enig open source er slet ikke målet det er midlet til mange ting.

Jeg tømmer lige hovedet:

- Kan hjælpe med at opfylde arkitekturmål i fælles rammearkitektur
- Værn mod korruption - fuld åbenhed
- Ansvarlig og bæredygtig produktion
- Øget innovation
- Medindflydelse
- Øge udviklingshastighed - time to market
- Kompetencer - viden flyder frit

**Comment by jeiby** [comment]
OK - indarbejdet, kan måske tydeliggøres i en senere version af vejledningen.
