### ISSUE TITLE
Adressér "myter" direkte

### ISSUE THREAD

**Issue by plimkilde** [rammearkitektur/open-source-guidance#17]
Under "Barrierer for offentlige myndigheders anvendelse af open source" er en række myter om open source opridset. Hvis vi har tænkt os at omtale disse, synes jeg hver af dem bør adresseres direkte - f.eks. at "open source er mindre sikker" bør have en tilhørende forklaring om at "security by obscurity" generelt ikke er accepteret som gangbar sikkerhedspraksis.

**Comment by jeiby** [comment]
Jeg har tænkt mig at indarbejde myterne i de forskellige afsnit rundt omkring frem for at have dem som et separat afsnit under anbefalinger.

**Comment by zorp** [comment]
Lyder som en god løsning at indarbejde i de forskellige afsnit - Hvor muligt.

Jeg har følgende input til myterne (https://github.com/rammearkitektur/open-source-guidance/blob/main/docs/02-recommendations.md#barrierer):

**Myte #1** - Der er i hundredvis af eksempler på at kritisk infrastruktur drives på open source software. De fleste af vores hjemmesider – de fleste servere som de hjemmesider kører på – Den infrastruktur som igen driver det Internet serverne skal køre på. Open Source indgår i stort set alt digitalt vi bruger – ikke nødvendigvis hele løsningen men så dele af løsningen.

**Myte #2** - Nogle løsninger har en høj teknisk barriere, ja – det gør sig også gældende for proprietær software. Rigtig mange open source løsninger leveres som færdig installationspakker hvor barrieren for ibrugtagning er lav.

**Myte #3** - Ingen udvikling er gratis – De fleste open source projekter eksistere fordi virksomheder er afhængige af løsningerne i deres forretning. De har derfor et incitament til at til bruge ressourcer på at vedligeholde og udvikle. Besparelsen ligger i høj grad i at man ikke er alene om at vedligeholde kildekoden. Når man tager eksisterende open source løsninger i brug er det derfor også vigtigt at forhold sig til hvordan man vil bidrage til projektet.

**Myte #4** - Hvis sikkerheden ligger i at man låser sin kildekode inde bag lås og slå så har man valgt en forkert sikkerhedsmodel. Security by obscrurity er der vist god evidens for ikke er vejen frem.

Ja for open source løsninger kan alle læse kildekoden – Men samtidig har alle seriøse open source projekter også defineret processer for hvordan sikkerhed håndteres. Derfor vil sikkerhedshuller også både blive fundet og rettet hurtigere. Dels er der flere øjne på kildekoden, dels giver den fulde åbenhed en større grundighed fra den enkelte bidragyder. Dels er der også flere og bedre muligheder til at opsætte automatiserede scanninger fordi kildekoden er frit tilgængelig og flere aktører kan scanne (Github gør det f.eks.). Der vil typisk være en langt højere grad af governance omkring et seriøst open source projekt. (ja så ville det være rart med et link til noget evidens).

**Myte 5** - Man kan lave vedligeholdelses- og supportaftaler på open-source software i samme grad som på standardsoftware. Nogle firmaer basere deres forretningsmodel på disse.

Endvidere har de største lige fra Microsoft, Google, Adobe, Spotify, Netflix, SAP, Twitter, Facebook, Amazon, Alibaba osv. osv. forretninger som afhænger af open source. Kigger man på hvor mange open source projekter de er med til aktivt at vedligehold eller direkte er ansvarlige for så tælles det i tusindvis.

**Myte 6** - Igen. Vi kan liste samtlige succesfulde teknologifirmaer og de har alle en open source strategi og interne open source ansvarlige. Det er en del af deres forretning at tjene penge på og med open source. Det giver dem tilmed en fordel i markedet.

**Comment by jeiby** [comment]
Myterne er taget under behandling i brødteksten, hvorfor afsnittet er fjernet, med undtagelse af sikkerhed gennem obskuritet, som behandles med henblik på en senere version af vejledningen.
