### ISSUE TITLE
EUs study about the impact of open source software and hardware...

### ISSUE THREAD

**Issue by zorp** [rammearkitektur/open-source-guidance#19]
Kunne evt. være relevant også at henvise til EU's undersøgelse af de økonomiske konsekvenser ved OS og særligt de 13 anbefalinger som rapporten kommer med. Findes i afsnit 9 fra side 314.

Rapporten: https://digital-strategy.ec.europa.eu/en/library/study-about-impact-open-source-software-and-hardware-technological-independence-competitiveness-and

**Comment by jeiby** [comment]
Vejledningen henviser til rapportens tre overskrifter for anbefalingerne, og DIGST/UAS kan efterfølgende vurdere, om der er behov for at være mere anvisende/normative i vejledningen - måske hvis der kommer en egentlig strategi for brug af open source?
