### ISSUE TITLE
Brug af andres opensource 

### ISSUE THREAD

**Issue by jabi27** [rammearkitektur/open-source-guidance#2]
Hos os (buvm) og sikkert i den største del af staten, er brugen af andres Opensouce produkter,
- linux
- databaser
- applikationservere 
- mm

langt større end tilfælde hvor vi laver vores eget opensouce projekt. Oftes vil vi bidrage til andres projekter med bugfixes og evt tilretninger, nye features mm.

Den del fylder ikke meget i dokumentet vs at etablere sit eget projekt. 

Vil det mon give mening at bruge lidt flere linjer på dette senarie?

/Jan Birk

**Comment by jeiby** [comment]
Brug af fælles open source-hardware er et interessant perspektiv. Jeg vil prøve at se, om EU-rapporten om samme har nogle gode pointer.

**Comment by zorp** [comment]
Jeg synes det er meget relevant at vejledningen også adressere hvad man bør overveje når man tager eksisterende open souce projekter i brug.

Hvordan vil man f.eks.:

- Selv bidrage: Økonomi, sponsorat, udviklingstimer, viden, eller måske slet ikke
- Vurdere om et projekt er bæredygtigt og har fungerende processer, community osv. - Altså at projektet vil fortsætte med at eksistere.

**Comment by jeiby** [comment]
OK
