### ISSUE TITLE
Anden analogi end "kigge under kølerhjelmen"

### ISSUE THREAD

**Issue by zorp** [rammearkitektur/open-source-guidance#20]
Kunne man i stedet bruge analogien ”læse og forstå opskriften” og dermed se hvordan løsningen eller softwaren er bygget.

Kigge under kølerhjelmen er også meget brugt men måske virkeligheden har indhentet den analogi - der er jo ikke meget at forstå og pille ved under kølerhjelmen i en moderne bil.

Eller måske er det bare navlepilleri fra min side :)

**Comment by jeiby** [comment]
Afsnittet er tilrettet derefter - navlepilleri eller ej ;-)
