### ISSUE TITLE
Open source er også underlagt copyright

### ISSUE THREAD

**Issue by zorp** [rammearkitektur/open-source-guidance#21]
i afsnittet Hvad er open source, https://github.com/rammearkitektur/open-source-guidance/blob/main/docs/01-introduction.md#hvad-er-open-source står at løsningen/softwaren ikke er underlagt copyright.

Copyright gælder fortsat for open source – Den enkelte biddragyder har copyright til eget bidrag men OS licensen har forgangsret og kan så tilsidesætte denne copyright ved at der give tillaldelse til at indholder frit bruges, deles, studere og ændres.

Forslag: da løsningen/softwaren er offentliggjort på en open source licens som muliggør at alle må bruge, studere, modificere og dele.

**Comment by jeiby** [comment]
Afsnittet er tilrettet derefter, og copyright nævnes nu ikke specifikt.
