### ISSUE TITLE
Faktaboks med eksempler på kendte OS applikationer/løsninger 

### ISSUE THREAD

**Issue by zorp** [rammearkitektur/open-source-guidance#22]
Forslag til applikationer:

Linux er allesteds nærværende som underliggende serversoftware og også som styresystem i OS2borgerPC

Libre- og openoffice - Men er nok i virkeligheden ikke så brugt fordi MS Office er defacto standarden.

Drupal benyttes af rigtig mange kommuner og andre offentlige myndigheder. Det samme gør Umbraco og sikkert også Wordpres.

QGIS har en bred anvendelse

ARCHI er i hvert fald kendt af IT-arkitekter, https://www.archimatetool.com/

OS2 produkterne

Det Digitale Folkebibliotek – DDB CMS

**Comment by jeiby** [comment]
Linux, LibreOffice, WordPress og OS2kitos er indarbejdet i teksten i faktaboksen.
