### ISSUE TITLE
Faktaboks: hvorfor ikke open source

### ISSUE THREAD

**Issue by zorp** [rammearkitektur/open-source-guidance#23]
Man skal jo altid vælge den bedste løsning til formålet og det er jo ikke nødvendigvis open source.

Et argument mod open source er de tilfælde hvor den lukkede løsning er markedsledende og en defacto standard. Eller når den lukkede løsning tilbyder den nemmeste og mest tilgængelige løsning for den almindelige bruger.

**Comment by jeiby** [comment]
Jeg har fjernet faktaboksen og i stedet lagt vægten andre steder på, at open source ikke altid er løsningen, men skal passe til og skabe værdi i den specifikke situation.
