### ISSUE TITLE
Etisk overvejelse ved IT-anskaffelse

### ISSUE THREAD

**Issue by zorp** [rammearkitektur/open-source-guidance#24]
Endvidere bør der indgå etiske overvejelser ved anskaffelsen. Er der f.eks. en etisk forpligtigelse til at sikre at den løsning som anskaffes nemt kan deles og ibrugtages af andre – Altså at vi ikke bruger skattekroner på det samme flere gange.

Og ved anskaffelser som involvere udvikling bør ligge en overvejelse om det man får udviklet er relevant for andre og man dermed bør sikre sig retten til at offentliggøre resultatet som Open Source

Man kan med fordel bruge et fællesskab som OS2 tidligt i ens anskaffelsesproces.

**Comment by jeiby** [comment]
Det bliver potentielt lidt for politisk, men jeg har indarbejdet noget om, at ønsket om stille software til rådighed for andre kan være en bevæggrund for at vælge at udvikle selv eller i fællesskab med andre.
