### ISSUE TITLE
Eksterne henvisninger under tjekliste til anskaffelse

### ISSUE THREAD

**Issue by zorp** [rammearkitektur/open-source-guidance#25]
Evt. henvise til andre kilder som supplerende materiale:

OS2s governance-tjekliste: https://github.com/OS2offdig/Governance_Reports

Standard for Public Code: https://standard.publiccode.net/ (en dansk oversættelse er også på vej)

**Comment by jeiby** [comment]
Der er henvist til begge materialer samt de italienske retningslinjer under Overvejelser om anskaffelse. Det lyder i øvrigt spændende, at der kommer en dansk oversættelse af standarden :-)
