### ISSUE TITLE
Kompetencer - Hvad skal der til

### ISSUE THREAD

**Issue by zorp** [rammearkitektur/open-source-guidance#26]
Det bør skrives ind at behovet for kompetencer også kan løftes i fællesskab. Her kan man med fordel bruge et fællesskab som OS2 til at varetage ansvaret. Eller en international pendant som f.eks. Foundation for Public Code.

Ansvaret med at kunne kontakte en leverandør kan man også vælge at placerer i egen baghave via f.eks. et fællesskab som OS2. Eller kombineret mellem et fællesskab og en leverandør.

Der står: _indkøb af kommerciel software har man ikke brug for at have alle kompetencerne internt_ - Det kan ikke stilles så sort/hvidt op at open source software kræver alle kompetencer kontra at kommerciel software ikke gør.
Der er massere af eksempler på leverandører som tilbyder open source software på samme vilkår som lukket kommerciel software. Og med open source har man også mulighed for at opbygge et fælleskab og leverandøraftaler som sikre at man ikke behøves besidde alle kompetencer selv.

Jeg synes det afsnit om kompetencer, måske særligt omkring de sidste to paragraffer er værd at nævne at det derfor også er vigtigt at man overvejer hvordan man organisere sig og sikrer at de nødvendige kompetencer er til stede.
Open Source modellen fordre at man samler sig i et fællesskab – målet er ikke at alle offentlige myndigheder alle har interne kompetencer til at mestre open source – Men det er vigtigt at man har et fælles organ som kan hjælpe. Jeg kan pege på OS2 som en mulighed.

Til faktaboks: Jeg synes selvfølgelig det vil være relevant at beskrive OS2 som et eksempel på et fællesskab der på tværs af organisationer kan løfte opgaven med de i afsnittet nævnte opgaver/kompetencer.

**Comment by jeiby** [comment]
Jeg har rettet til i afsnittet, så det nu afspejler, at der ikke nødvendigvis er større kompetencebehov ved brug af open source - måske faktisk et potentielt mindre kompetence_tab_ - og at man med fordel kan lægge nogle af kompetencerne over i fællesskabet, eller trække på andre derigennem.
