### ISSUE TITLE
Forankring af open source i topledelsen

### ISSUE THREAD

**Issue by jeiby** [rammearkitektur/open-source-guidance#6]
Open source skal ikke realiseres som en teknologisk landvinding, men skal ”ud af it-værkstedet” og ind på direktørkontoret. Forankring af open source i topledelsen. Måske trække på udenlandske erfaringer?

**Comment by zorp** [comment]
Her handler det om at binde det op på andre ting end teknik. Hvilke udfordringer kan OS være med til at løse.

Den italienske lovgivning er i høj grad kørt igennem som et værn mod korruption.

**Comment by jeiby** [comment]
OK
